---
name: Test

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install SWIG
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: brew install swig

      - name: Install Piper
        run: |
          script/setup --dev
          script/dev_build

      - name: Run tests
        run: script/test
