name: Test

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install Piper
        run: python -m pip install .[dev]

      - name: Run tests
        run: pytest -vv tests
