---
name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Piper
        run: |
          script/setup --dev
          script/dev_build

      - name: Build wheels
        run: |
          script/package

      - uses: actions/upload-artifact@v4
        with:
          name: piper-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
